name: championship_manager
description: Gerenciador de campeonatos de esportes

environment:
  sdk: '>=3.4.0 <8.0.0'  # Adicione a restrição mínima para o SDK

dependencies:
  flutter:
    sdk: flutter

  parse_server_sdk_flutter: ^8.0.0  # Atualize para a versão mais recente

  http: ^0.13.6

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


